comercio/comercio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include("products.urls")),
    path('suppliers/', include("suppliers.urls"))
]

comercio/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="productregistry"),
    path('add/addproduct/', views.saveproduct, name="savenewproduct"),
    path('delete/<int:id>', views.delete, name='delete'),
    path('update/<int:id>', views.update, name='update'),
    path('update/updaterecord/<int:id>', views.updaterecord, name='updaterecord'),
    path('search/', views.search, name="searchproduct"),
    path('suppliersOfProduct/<int:pk>', views.suppliers_of_product, name='suppliers_of_product'),
    path('buyStock/', views.buyStock, name='buyStock'),
    path('buyProduct/<int:id>', views.buyProduct, name='buyProduct')
]

comercio/suppliers/urls.py
from django.urls import path
from . import views

app_name = 'suppliers'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('add/', views.CadastroFornecedorView.as_view(), name="supplierregistry"),
    path('search/', views.SearchView.as_view(), name='search'),
    path('delete/<int:pk>', views.DeletarFornecedorView.as_view(), name='delete'),
    path('update/<int:pk>', views.AtualizarFornecedorView.as_view(), name='update'),
    path('registerProduct/', views.product_to_supplier_view, name='product_to_supplier'),
    path('registerProducts/', views.register_products_to_supplier, name='register_products_to_supplier'),
    path('unregisterProduct/', views.remove_product_to_supplier_view, name='remove_product_of_supplier'),
    path('unregisterProducts/', views.remove_products_of_supplier, name='unregister_products_to_supplier'),
]

comercio/suppliers/models.py
from django.db import models
from django.urls import reverse
from products.models import Product

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=255)
    telephone = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    products = models.ManyToManyField(Product)

    def get_absolute_url(self):
        return reverse('suppliers:update', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name+":"+self.cnpj
    
    def __eq__(self, obj):
        if isinstance(obj, Supplier):
            conditions = [obj.name == self.name,
                            obj.telephone == self.telephone,
                            obj.cnpj == self.cnpj,
                            obj.address == self.address
                        ]
            return all(conditions)
        else:
            return False
    
    def __hash__(self):
        return super().__hash__()

comercio/suppliers/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import  reverse_lazy, reverse
from django.views import generic
from .models import Supplier
from products.models import Product
from django.template import loader


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'suppliers/index.html'
    context_object_name = "suppliers_list"

    def get_queryset(request):
        return Supplier.objects.all()

class SearchView(generic.ListView):
    template_name = 'suppliers/search.html'
    context_object_name = "suppliers_list"

    def get_queryset(self):
        return Supplier.objects.filter(name__icontains = self.request.GET['name']).values()

class CadastroFornecedorView(generic.CreateView):
    template_name_suffix = '_create_form'
    model = Supplier
    fields = ['name','telephone','cnpj','address']

class DeletarFornecedorView(generic.DeleteView):
    model = Supplier
    success_url = reverse_lazy('suppliers:index')

class AtualizarFornecedorView(generic.UpdateView):
    model = Supplier
    fields = ['name','cnpj','telephone','address']
    template_name_suffix = '_update_form'

    success_url = reverse_lazy('suppliers:index')

def product_to_supplier_view(request):
    template = loader.get_template("suppliers/productToSupplier.html")
    myproducts = Product.objects.all()

    supId = request.GET['supplierId']

    supplier = Supplier.objects.get(pk=supId)

    supProducts = supplier.products.all()

    productsToShow = []

    for product in myproducts:
        if product not in supProducts:
            productsToShow.append(product)

    context = {
        "myproducts": productsToShow,
        "supplierId": supId
    }

    return HttpResponse(template.render(context, request))

def register_products_to_supplier(request):
    checkboxArgs = [arg for arg in list(request.POST.keys()) if arg[:8] == 'checked-'] 
    mySup = Supplier.objects.get(pk=request.POST['supId'])
    for checkboxName in checkboxArgs:
        checkBoxValue = request.POST[checkboxName]
        mySup.products.add(Product.objects.get(pk=checkBoxValue))

    return HttpResponseRedirect(reverse('suppliers:index'))

def remove_product_to_supplier_view(request):
    template = loader.get_template("suppliers/products_of_supplier.html")

    supId = request.GET['supplierId']

    supplier = Supplier.objects.get(pk=supId)

    context = {
        "supplier": supplier
    }

    return HttpResponse(template.render(context, request))

def remove_products_of_supplier(request):
    checkboxArgs = [arg for arg in list(request.POST.keys()) if arg[:8] == 'checked-'] 
    mySup = Supplier.objects.get(pk=request.POST['supId'])
    for checkboxName in checkboxArgs:
        checkBoxValue = request.POST[checkboxName]
        mySup.products.remove(Product.objects.get(pk=checkBoxValue))

    return HttpResponseRedirect(reverse('suppliers:index'))

comercio/suppliers/templates/suppliers/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Fornecedores</title>
        <meta charset="UTF-8">
        {% include 'suppliers/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'suppliers/menu.html' %}
            <hr />
            <div class="w3-container">

                {% if suppliers_list %}
                    <div class="w3-row w3-container w3-margin-bottom">
                        <form action="{% url 'suppliers:search' %}" method="get">
                            <div class="w3-col l10 w3-container w3-center w3-padding">       
                                {% csrf_token %}
                                <input class="w3-input w3-border w3-round-xlarge" type="text" name="name" placeholder="Nome do Fornecedor">
                            </div>
                            <div class="w3-col l2 w3-center w3-padding">
                                <input type="submit" value="Pesquisar" class="w3-button w3-indigo w3-border w3-round-xlarge" >
                            </div>
                        </form>
                    </div>
                    <table class="w3-table w3-striped w3-bordered">
                        <thead class="w3-green">
                            <th></th>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Telefone</th>
                            <th>CNPJ</th>
                            <th>Endereço</th>
                            <th>Ação</th>
                        </thead>
                        {% for x in suppliers_list %}
                        <tr class="w3-center">
                            <td><a href="{% url 'suppliers:update' x.id %}"><i class="fa fa-pencil w3-text-indigo"></i> Ações</a></td>
                            <td>{{ x.id }}</td>
                            <td>{{ x.name }}</td>
                            <td>{{ x.telephone }}</td>
                            <td>{{ x.cnpj }}</td>
                            <td>{{ x.address }}</td>
                            <td><a href="{% url 'suppliers:delete' x.id %}"><i class="fa fa-trash w3-text-red"></i></a></td>
                        </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <div class="w3-row">
                        <div class="w3-col l3"><br /></div>
                        <div class="w3-col l6">
                            <div class="w3-panel w3-white w3-bottombar w3-border-amber w3-border">
                                <p>Não existem fornecedores cadastrados.</p>
                            </div>
                        </div>
                        <div class="w3-col l3"><br /></div>
                    </div>
                {% endif %}
                <div class="w3-col l6 w3-right w3-container w3-padding">
                    <a href="{% url 'suppliers:supplierregistry'%}" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top w3-right">
                        <i class="fa fa-plus w3-text-white"></i> Cadastrar fornecedor</a>
                </div>
            </div>
        </div>
    </body>
</html>

comercio/suppliers/templates/suppliers/links.html
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<script src="https://use.fontawesome.com/7875b93e0a.js"></script>

comercio/suppliers/templates/suppliers/menu.html
<div class="w3-row w3-large w3-light-green">
    <div class="w3-col s2">
        <a href="{% url 'products:index'%}" class="w3-button w3-block">Produtos</a>
    </div>
    <div class="w3-col s3">
        <a href="{% url 'suppliers:index'%}" class="w3-button w3-block  w3-indigo">Fornecedores</a>
    </div>
</div>

<div class="w3-content" style="max-width:1100px; margin-top:10px;">
    <div class="w3-panel w3-center">
        <img src="http://ricardo.bib.br/logo_t.png" class="w3-center" width="200px" >
    </div>

comercio/suppliers/templates/suppliers/productToSupplier.html
<!DOCTYPE html>
<html>
    <head>
        <title>Cadastro de Produto em Fornecedor</title>
        <meta charset="UTF-8">
        {% include 'suppliers/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'suppliers/menu.html' %}
            <div class="w3-container">

                <h3 class="w3-text-green">Cadastro de Produto em Fornecedor</h1>
                {% if myproducts %}
                <form action="{% url 'suppliers:register_products_to_supplier' %}" method="POST">
                    {% csrf_token%}
                    <table class="w3-table w3-striped w3-bordered">
                        <thead class="w3-green">
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Preço</th>
                            <th>Marca</th>
                            <th>Estoque</th>
                            <th>Vendidos</th>
                            <th>Selecionar</th>
                        </thead>
                            {% for x in myproducts%}
                                <tr>
                                    <td>{{x.id}}</td>
                                    <td>{{x.name}}</td>
                                    <td>{{x.price}}</td>
                                    <td>{{x.brand}}</td>
                                    <td>{{x.stock}}</td>
                                    <td>{{x.sold}}</td>
                                    <td>
                                        <input type="checkbox" name="checked-{{forloop.counter0}}" id="checked-{{forloop.counter0}}" value="{{x.id}}">
                                    </td>
                                </tr>
                            {% endfor %}
                    </table>
                    <input type="hidden" name="supId" value="{{supplierId}}">
                    <br>
                    <div class="w3-row w3-margin-bottom w3-center">
                        <input type="submit" name="cadastrar" id="cadastrar" value="Cadastrar Selecionados" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top">
                    </div>
                </form>
                {% else %}
                    <div class="w3-row">
                        <div class="w3-col l3"><br /></div>
                        <div class="w3-col l6">
                            <div class="w3-panel w3-white w3-bottombar w3-border-amber w3-border">
                                <p>Não existem produtos cadastrados e que sejam diferentes dos que já estejam associados ao Fornecedor.</p>
                            </div>
                        </div>
                        <div class="w3-col l3"><br /></div>
                    </div>
                {% endif %}
                <br>
                <div class="w3-left">
                    <a href="{% url 'suppliers:index' %}"
                    class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top"><i class="fa fa-arrow-left"></i> Voltar</a>
                </div>
            </div>
        </div>
    </body>
</html>

comercio/suppliers/templates/suppliers/products_of_supplier.html
<!DOCTYPE html>
<html>
    <head>
        <title>Fornecedores</title>
        <meta charset="UTF-8">
        {% include 'suppliers/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'suppliers/menu.html' %}
            <div class="w3-container">

                <h3 class="w3-text-green">Remover Produto de Fornecedor</h1>
                {% if supplier.products.all %}
                <form action="{% url 'suppliers:unregister_products_to_supplier' %}" method="POST">
                    {% csrf_token%}
                    <table class="w3-table w3-striped w3-bordered">
                        <thead class="w3-green">
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Preço</th>
                            <th>Marca</th>
                            <th>Estoque</th>
                            <th>Vendidos</th>
                            <th>Selecionar</th>
                        </thead>
                        <tbody>
                            {% for x in supplier.products.all%}
                                <tr>
                                    <td>{{x.id}}</td>
                                    <td>{{x.name}}</td>
                                    <td>{{x.price}}</td>
                                    <td>{{x.brand}}</td>
                                    <td>{{x.stock}}</td>
                                    <td>{{x.sold}}</td>
                                    <td>
                                        <input type="checkbox" name="checked-{{forloop.counter0}}" id="checked-{{forloop.counter0}}" value="{{x.id}}">
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <br>
                    <input type="hidden" name="supId" value="{{supplier.id}}">
                    <div class="w3-row w3-margin-bottom w3-center">
                        <input type="submit" name="remover" id="remover" value="Remover Selecionados" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top">
                    </div>
                </form>
                {% else %}
                    <div class="w3-row">
                        <div class="w3-col l3"><br /></div>
                        <div class="w3-col l6">
                            <div class="w3-panel w3-white w3-bottombar w3-border-amber w3-border">
                                <p>Não existem produtos cadastrados para esse Fornecedor.</p>
                            </div>
                        </div>
                        <div class="w3-col l3"><br /></div>
                    </div>
                {% endif %}
                <br>
                <div class="w3-left">
                    <a href="{% url 'suppliers:index' %}"
                    class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top"><i class="fa fa-arrow-left"></i> Voltar ao index</a>
                </div>
            </div>
        </div>
    </body>
</html>

comercio/suppliers/templates/suppliers/search.html
<!DOCTYPE html>
<html>
    <head>
        <title>Pesquisa de Fornecedor</title>
        <meta charset="UTF-8">
        {% include 'suppliers/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'suppliers/menu.html' %}
            <hr />
            <div class="w3-container">
                <h3 class="w3-text-green">Fornecedores Encontrados</h1>
                {% if suppliers_list %}
                    <table class="w3-table w3-striped w3-bordered">
                        <thead class="w3-green">
                            <th></th>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Telefone</th>
                            <th>CNPJ</th>
                            <th>Endereço</th>
                            <th>Ação</th>
                        </thead>
                        {% for x in suppliers_list %}
                        <tr class="w3-center">
                            <td><a href="{% url 'suppliers:update' x.id %}"><i class="fa fa-pencil w3-text-indigo"></i> Ações</a></td>
                            <td>{{ x.id }}</td>
                            <td>{{ x.name }}</td>
                            <td>{{ x.telephone }}</td>
                            <td>{{ x.cnpj }}</td>
                            <td>{{ x.address }}</td>
                            <td><a href="{% url 'suppliers:delete' x.id %}">Deletar</a></td>
                        </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <div class="w3-row">
                        <div class="w3-col l3"><br /></div>
                        <div class="w3-col l6">
                            <div class="w3-panel w3-white w3-bottombar w3-border-amber w3-border">
                                <p>Não existem fornecedores cadastrados com o nome pesquisado.</p>
                            </div>
                        </div>
                        <div class="w3-col l3"><br /></div>
                    </div>
                {% endif %}
                <div class="w3-left">
                    <a href="{% url 'suppliers:index' %}"
                    class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top"><i class="fa fa-arrow-left"></i> Voltar ao index</a>
                </div>
            </div>
        </div>
    </body>
</html>

comercio/suppliers/templates/suppliers/supplier_confirm_delete.html
<!DOCTYPE html>
<html>
    <head>
        <title>Confirmar Deleção</title>
        <meta charset="UTF-8">
        {% include 'suppliers/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'suppliers/menu.html' %}
            <hr />
            <div class="w3-container">
                <h3 class="w3-text-green">Confirmar Deleção</h1>
                <form method="post">
                    {% csrf_token %}
                    <p>Tem certeza que quer deletar o Fornecedor com os seguintes dados:</p>
                    <table class="w3-table w3-striped w3-bordered">
                        <thead class="w3-green">
                            <th>Nome</th>
                            <th>CNPJ</th>
                            <th>Telefone</th>
                            <th>Endereço</th>
                        </thead>
                        <tr class="w3-center">
                            <td>{{ object.name }}</td>
                            <td>{{ object.cnpj }}</td>
                            <td>{{ object.telephone }}</td>
                            <td>{{ object.address }}</td>
                        </tr>
                    </table>
                    {{ form }}
                    <div class="w3-row w3-margin-bottom w3-center">
                        <input type="submit" value="Confirmar" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top">
                    </div>
                </form>
                <div class="w3-left">
                    <a href="{% url 'suppliers:index' %}"
                    class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top"><i class="fa fa-arrow-left"></i> Voltar ao index</a>
                </div>
            </div>
        </div>
    </body>
</html>

comercio/suppliers/templates/suppliers/supplier_create_form.html
<!DOCTYPE html>
<html>
    <head>
        <title>Cadastro de Fornecedor</title>
        <meta charset="UTF-8">
        {% include 'suppliers/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'suppliers/menu.html' %}

            <div class="w3-container">
                {% if messages %}
                <div class="w3-panel w3-pale-red">
                    <ul class="w3-ul messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                    </ul>
                </div>
                {% endif %}

                <div class="w3-bar w3-green">
                    <span class="w3-xlarge w3-bar-item ">Cadastro de Fornecedor</span>
                </div>
                
                <div class="w3-container w3-border w3-border-xround">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="w3-container w3-margin-bottom w3-center">
                            <input type="submit" value="Cadastrar" class="w3-button w3-lime w3-border w3-round-xlarge w3-margin-top">
                        </div>
                    </form>
                </div>
                <div class="w3-left">
                    <a href="{% url 'suppliers:index' %}"
                    class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top"><i class="fa fa-arrow-left"></i> Voltar ao index</a>
                </div>
            </div>
        </div>
    </body>
</html>

comercio/suppliers/templates/suppliers/supplier_update_form.html
<!DOCTYPE html>
<html>
    <head>
        <title>Fornecedor</title>
        <meta charset="UTF-8">
        {% include 'suppliers/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'suppliers/menu.html' %}

            <div class="w3-margin">
                {% if messages %}
                <div class="w3-panel w3-pale-red">
                    <ul class="w3-ul messages">
                        {% for message in messages %}
                        
                        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                    </ul>
                </div>
                {% endif %}

                <p>
                    <b>Fornecedor: </b>{{ supplier.name }} ({{ supplier.cnpj }})<br/>
                    <b>Telefone: </b>{{ supplier.telephone }}<br/>
                    <b>Endreço: </b>{{ supplier.address }}<br/>
                </p>

                <div class="w3-container">
                    <div class="w3-bar w3-green">
                        <button class="w3-bar-item w3-button tablink" onclick="openAction(event, 'Atualizar')">Atualizar Fornecedor</button>
                        <button class="w3-bar-item w3-button tablink" onclick="openAction(event, 'Produtos')">Produtos do Fornecedor</button>
                    </div>
                    
                    <div id="Atualizar" class="w3-container w3-border acao" style="display:none">
                        <form method="post"> 
                            {% csrf_token %} 
                            {{ form.as_p }} 
                            <br>
                            <div class="w3-row w3-margin-bottom w3-center">
                                <input type="submit" value="Atualizar Fornecedor" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top">
                            </div>
                        </form> 
                    </div>
                    
                    <div id="Produtos" class="w3-container w3-border acao" style="display:none">
                        <p>Produtos cadastrados a esse Fornecedor</p>
                        {% if object.products.all %}
                            
                            <table class="w3-table w3-striped w3-bordered">
                                <thead class="w3-light-green">
                                    <th>Id</th>
                                    <th>Nome</th>
                                    <th>Preço</th>
                                    <th>Marca</th>
                                    <th>Estoque</th>
                                    <th>Vendidos</th>
                                </thead>
                                {% for product in object.products.all%}
                                    <tr>
                                        <td>{{product.id}}</td>
                                        <td>{{product.name}}</td>
                                        <td>{{product.price}}</td>
                                        <td>{{product.brand}}</td>
                                        <td>{{product.stock}}</td>
                                        <td>{{product.sold}}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                            <br/>
                            <div class="w3-container w3-margin-bottom w3-center">
                                <form action="{% url 'suppliers:remove_product_of_supplier'%}" style="display: inline;">
                                    <input type="submit" value="Desassociar um Produto"  class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top" />
                                    <input type="hidden" name="supplierId" id="supplierId" value="{{object.id}}">
                                </form>
                                <form action="{% url 'suppliers:product_to_supplier'%}" style="display: inline;">
                                    <input type="submit" value="Cadastrar Novo Produto"  class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top" />
                                    <input type="hidden" name="supplierId" id="supplierId" value="{{object.id}}" >
                                </form>
                            </div>
                        {%else %}
                            <div class="w3-row">
                                <div class="w3-col l3"><br /></div>
                                <div class="w3-col l6">
                                    <div class="w3-panel w3-white w3-bottombar w3-border-amber w3-border">
                                        <p>Não existem produtos associados para esse Fornecedor.</p>
                                    </div>
                                </div>
                                <div class="w3-col l3"><br /></div>
                            </div>
                            <div class="w3-container w3-margin-bottom w3-center">
                                <form action="{% url 'suppliers:product_to_supplier'%}" style="display: inline;">
                                    <input type="submit" value="Cadastrar Novo Produto"  class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top" />
                                    <input type="hidden" name="supplierId" id="supplierId" value="{{object.id}}" >
                                </form>
                            </div>
                        {% endif %}
                        <br>
                    </div>
                </div>
                <p>
                    <a href="{% url 'suppliers:index' %}" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top"><i class="fa fa-arrow-left"></i> Voltar</a>
                </p>
            </div> 
        </div>
    </body>
    <script>
        function openAction(evt, acaoName) {
            var i, x, tablinks;
            x = document.getElementsByClassName("acao");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablink");
            for (i = 0; i < x.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" w3-indigo", "");
            }
            document.getElementById(acaoName).style.display = "block";
            evt.currentTarget.className += " w3-indigo";
        }
    </script>
</html>