comercio/comercio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include("products.urls")),
    path('suppliers/', include("suppliers.urls"))
]

comercio/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="productregistry"),
    path('add/addproduct/', views.saveproduct, name="savenewproduct"),
    path('delete/<int:id>', views.delete, name='delete'),
    path('update/<int:id>', views.update, name='update'),
    path('update/updaterecord/<int:id>', views.updaterecord, name='updaterecord'),
    path('search/', views.search, name="searchproduct"),
    path('suppliersOfProduct/<int:pk>', views.suppliers_of_product, name='suppliers_of_product'),
    path('buyStock/', views.buyStock, name='buyStock'),
    path('buyProduct/<int:id>', views.buyProduct, name='buyProduct')
]

comercio/suppliers/urls.py
from django.urls import path
from . import views

app_name = 'suppliers'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('add/', views.CadastroFornecedorView.as_view(), name="supplierregistry"),
    path('search/', views.SearchView.as_view(), name='search'),
    path('delete/<int:pk>', views.DeletarFornecedorView.as_view(), name='delete'),
    path('update/<int:pk>', views.AtualizarFornecedorView.as_view(), name='update'),
    path('registerProduct/', views.product_to_supplier_view, name='product_to_supplier'),
    path('registerProducts/', views.register_products_to_supplier, name='register_products_to_supplier'),
    path('unregisterProduct/', views.remove_product_to_supplier_view, name='remove_product_of_supplier'),
    path('unregisterProducts/', views.remove_products_of_supplier, name='unregister_products_to_supplier'),
]

comercio/products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    brand = models.CharField(max_length=255)
    stock = models.PositiveIntegerField()
    sold = models.PositiveIntegerField()

    def __str__(self):
        return self.name+":"+self.brand

comercio/suppliers/models.py
from django.db import models
from django.urls import reverse
from products.models import Product

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=255)
    telephone = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    products = models.ManyToManyField(Product)

    def get_absolute_url(self):
        return reverse('suppliers:update', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name+":"+self.cnpj
    
    def __eq__(self, obj):
        if isinstance(obj, Supplier):
            conditions = [obj.name == self.name,
                            obj.telephone == self.telephone,
                            obj.cnpj == self.cnpj,
                            obj.address == self.address
                        ]
            return all(conditions)
        else:
            return False
    
    def __hash__(self):
        return super().__hash__()

comercio/products/views.py
from json import load
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Product
from suppliers.models import Supplier
from django.urls import reverse
from django.contrib import messages

# Create your views here.
def index(request):
    template = loader.get_template("products/index.html")
    myproducts = Product.objects.all().values()

    context = {
        "myproducts": myproducts,
    }

    return HttpResponse(template.render(context, request))

def add(request):
    template = loader.get_template("products/addProduct.html")
    return HttpResponse(template.render({}, request))

def saveproduct(request):
    nome = request.POST['name']
    preco = request.POST['price']
    marca = request.POST['brand']
    estoque = 0
    vendidos = 0
    try:
        novoProduto = Product(name=nome, price=preco, brand=marca, stock=estoque, sold=vendidos)
        novoProduto.save()
    except:
        messages.error(request, "Complete corretamente todos os campos de cadastro!")
        return HttpResponseRedirect(reverse("products:productregistry"))
    else:
        return HttpResponseRedirect(reverse("products:index"))

def delete(request, id):
  produto = Product.objects.get(id=id)
  produto.delete()
  return HttpResponseRedirect(reverse('products:index'))

def update(request, id):
  myproduct = Product.objects.get(id=id)
  template = loader.get_template('products/update.html')
  context = {
    'myproduct': myproduct,
  }
  return HttpResponse(template.render(context, request))

def updaterecord(request, id):
    nome = request.POST['name']
    marca = request.POST['brand']
    preco = request.POST['price']

    try:
        produto = Product.objects.get(id=id)
        produto.name = nome
        produto.brand = marca
        produto.price = preco

        produto.save()
    except:
        messages.error(request, "Complete corretamente todos os campos de cadastro!")
        return HttpResponseRedirect(reverse("products:update", kwargs={'id':id}))
    else:
    
        return HttpResponseRedirect(reverse('products:index'))

def search(request):
    nome = request.POST['name']
    template = loader.get_template('products/searchProduct.html')

    myproductsearch = Product.objects.filter(name__icontains=nome)

    context = {
        'myproductsearch': myproductsearch,
    }

    return HttpResponse(template.render(context, request))    

def suppliers_of_product(request, pk):
    template = loader.get_template('products/suppliers_of_product.html')
    prodId = pk
    product = Product.objects.get(pk=prodId)

    context = {'product':product}
    return HttpResponse(template.render(context, request))

def buyStock(request):
    prodId = request.POST['prodId']
    supToBuy = 0
    stockToBuy = 0
    try:
        supToBuy = int(request.POST['supplier'])
    except:
        messages.error(request, "Selecione um Fornecedor para comprar")
        return HttpResponseRedirect(reverse("products:suppliers_of_product", kwargs={'pk':prodId}))
    else:
        product = Product.objects.get(pk=prodId)

        if product.supplier_set:
            suppliers_of_product = product.supplier_set.all()
            ids_suppliers_of_product = set(map(lambda sup: sup.id, suppliers_of_product))

            if supToBuy not in ids_suppliers_of_product:
                messages.error(request, "Não é possível comprar estoque de um fornecedor não associado")
                return HttpResponseRedirect(reverse("products:suppliers_of_product", kwargs={'pk':prodId}))

        else:
            messages.error(request, "Não é possível comprar estoque de um fornecedor não associado")
            return HttpResponseRedirect(reverse("products:suppliers_of_product", kwargs={'pk':prodId}))

        try:
            stockToBuy = int(request.POST['stockToBuy'])

            if stockToBuy < 1:
                raise ValueError("Tentativa de comprar estoque não positivo")
                
        except:
            messages.error(request, "Digite apenas números inteiros positivos no estoque!")
            return HttpResponseRedirect(reverse("products:suppliers_of_product", kwargs={'pk':prodId}))
        else:
            product.stock += stockToBuy
            product.save()
            return HttpResponseRedirect(reverse('products:index'))
    
def buyProduct(request, id):
    quantidadeComprada = request.POST['quantidade']

    try:
        quantidadeComprada = int(quantidadeComprada)
    except:
        messages.error(request, "Digite um número inteiro como quantidade para comprar!")
    else:
        product = Product.objects.get(pk=id)
        if product.stock < quantidadeComprada:
            messages.error(request, "A quantidade comprada excede o estoque atual!")
        elif quantidadeComprada <= 0:
            messages.error(request, "A quantidade comprada deve ser um número positivo!")
        else:
            product.stock -= quantidadeComprada
            product.sold += quantidadeComprada
            product.save()
            messages.success(request, "Produto comprado com sucesso!")
        
    finally:
        return HttpResponseRedirect(reverse("products:update", kwargs={'id':id}))

comercio/products/templates/products/addProduct.html
<!DOCTYPE html>
<html>
    <head>
        <title>Produtos</title>
        <meta charset="UTF-8">
        {% include 'products/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'products/menu.html' %}

            <div class="w3-container">
                {% if messages %}
                <div class="w3-panel w3-pale-red">
                    <ul class="w3-ul messages">
                        {% for message in messages %}
                        
                        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                    </ul>
                </div>
                {% endif %}

                <div class="w3-bar w3-green">
                    <span class="w3-xlarge w3-bar-item ">Adicione um novo produto</span>
                </div>
                
                <div class="w3-container w3-border w3-border-xround">
                    <form action="{% url 'products:savenewproduct' %}" method="post">
                        {% csrf_token %}
                        <div class="w3-row w3-margin-top">
                            <div class="w3-col l6 w3-container">
                                <label>Nome:</label><br>
                                <input class="w3-input w3-border w3-border-xlarge" name="name" 
                                    id="name_field" placeholder="Digite um nome" required>
                            </div>
                            <div class="w3-col l6">
                                <label>Preço:</label><br>
                                <input class="w3-input w3-border w3-border-xlarge" name="price"
                                    id="price_field" placeholder="Digite um preço" required>
                            </div>
                        </div>
                        <div class="w3-row w3-margin-top">
                            <div class="w3-col l6  w3-container">
                                <label>Marca:</label><br>
                                <input class="w3-input w3-border w3-border-xlarge" name="brand"
                                    id="brand_field" placeholder="Digite o nome da marca do produto" required>
                            </div>
                        </div>
                        <div class="w3-container w3-margin-bottom w3-center">
                            <input type="submit" value="Cadastrar" class="w3-button w3-lime w3-border w3-round-xlarge w3-margin-top">
                        </div>
                    </form>
                </div>
                <div class="w3-left">
                    <a href="{% url 'products:index' %}"
                    class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top"><i class="fa fa-arrow-left"></i> Voltar</a>
                </div>
            </div>
        </div>
    </body>
</html>

comercio/products/templates/products/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Produtos</title>
        <meta charset="UTF-8">
        {% include 'products/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'products/menu.html' %}
            <hr />
            <div class="w3-container">

                {% if myproducts %}
                    <div class="w3-row w3-container w3-margin-bottom">
                        <form action="{% url 'products:searchproduct' %}" method="post">
                            <div class="w3-col l10 w3-container w3-center w3-padding">       
                                {% csrf_token %}
                                <input class="w3-input w3-border w3-round-xlarge" type="text" name="name" placeholder="Pesquisar pelo nome do Produto">
                            </div>
                            <div class="w3-col l2 w3-center w3-padding">
                                <input type="submit" value="Pesquisar" class="w3-button w3-indigo w3-border w3-round-xlarge" >
                            </div>
                        </form>
                    </div>
                    <table class="w3-table w3-striped w3-bordered">
                        <thead class="w3-green">
                            <th></th>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Marca</th>
                            <th>Preço</th>
                            <th>Estoque</th>
                            <th>Vendidos</th>
                            <th></th>
                        </thead>
                        {% for x in myproducts %}
                        <tr class="w3-center">
                            <td><a href="{% url 'products:update' x.id %}"><i class="fa fa-pencil w3-text-indigo"></i> Ações</a></td>
                            <td>{{ x.id }}</td>
                            <td>{{ x.name }}</td>
                            <td>{{ x.brand }}</td>
                            <td>{{ x.price }}</td>
                            <td>{{ x.stock }}</td>
                            <td>{{ x.sold }}</td>
                            <td><a href="{% url 'products:delete' x.id %}" ><i class="fa fa-trash w3-text-red"></i></a></td>
                            
                        </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <div class="w3-row">
                        <div class="w3-col l3"><br /></div>
                        <div class="w3-col l6">
                            <div class="w3-panel w3-white w3-bottombar w3-border-amber w3-border">
                                <p>Não existem produtos cadastrados no sistema.</p>
                            </div>
                        </div>
                        <div class="w3-col l3"><br /></div>
                    </div>
                {% endif %}


                <div class="w3-col l6 w3-right w3-container w3-padding">
                    <a href="{% url 'products:productregistry' %}" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top w3-right">
                        <i class="fa fa-plus w3-text-white"></i> Adicionar produto</a>
                </div>
            </div>
        </div>
    </body>
</html>

comercio/products/templates/products/links.html
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<script src="https://use.fontawesome.com/7875b93e0a.js"></script>

comercio/products/templates/products/menu.html
<div class="w3-row w3-large w3-light-green">
    <div class="w3-col s2">
        <a href="{% url 'products:index'%}" class="w3-button w3-block  w3-indigo">Produtos</a>
    </div>
    <div class="w3-col s3">
        <a href="{% url 'suppliers:index'%}" class="w3-button w3-block">Fornecedores</a>
    </div>
</div>

<div class="w3-content" style="max-width:1100px; margin-top:10px;">
    <div class="w3-panel w3-center">
        <img src="http://ricardo.bib.br/logo_t.png" class="w3-center" width="200px" >
    </div>

comercio/products/templates/products/searchProduct.html
<!DOCTYPE html>
<html>
    <head>
        <title>Produtos</title>
        <meta charset="UTF-8">
        {% include 'products/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'products/menu.html' %}

            <div class="w3-container">

                {% if myproductsearch %}
                    <table class="w3-table w3-striped w3-bordered">
                        <thead class="w3-green">
                            <th></th>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Marca</th>
                            <th>Preço</th>
                            <th>Estoque</th>
                            <th>Vendidos</th>
                            <th></th>
                        </thead>
                        {% for x in myproductsearch %}
                        <tr class="w3-center">
                            <td><a href="{% url 'products:update' x.id %}"><i class="fa fa-pencil w3-text-indigo"></i> Ações</a></td>
                            <td>{{ x.id }}</td>
                            <td>{{ x.name }}</td>
                            <td>{{ x.brand }}</td>
                            <td>{{ x.price }}</td>
                            <td>{{ x.stock }}</td>
                            <td>{{ x.sold }}</td>
                            <td><a href="{% url 'products:delete' x.id %}" ><i class="fa fa-trash w3-text-red"></i></a></td>
                            
                        </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <div class="w3-row">
                        <div class="w3-col l3"><br /></div>
                        <div class="w3-col l6">
                            <div class="w3-panel w3-white w3-bottombar w3-border-amber w3-border">
                                <p><p>Não existem produtos cadastrados com este nome.</p></p>
                            </div>
                        </div>
                        <div class="w3-col l3"><br /></div>
                    </div>
                {% endif %}
                <p>
                    <a href="{% url 'products:index' %}" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top"><i class="fa fa-arrow-left"></i> Voltar</a>
                </p>
            </div>
        </div>
    </body>
</html>

comercio/products/templates/products/suppliers_of_product.html
<!DOCTYPE html>
<html>
    <head>
        <title>Produtos</title>
        <meta charset="UTF-8">
        {% include 'products/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'products/menu.html' %}

            <div class="w3-container">
                {% if messages %}
                <div class="w3-panel w3-pale-red">
                    <ul class="w3-ul messages">
                        {% for message in messages %}
                        
                        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                    </ul>
                </div>
                {% endif %}

                <div class="w3-bar w3-green">
                    <span class="w3-xlarge w3-bar-item ">Comprar Estoque</span>
                </div>
                
                <div class="w3-container w3-border w3-border-xround">

                    <br/>
                    {% if product.supplier_set.all%}
                    <form action="{% url 'products:buyStock'%}" method="POST">
                        {%csrf_token%}
                        <table class="w3-table w3-striped w3-bordered">
                            <thead class="w3-light-green">
                                <th>Nome</th>
                                <th>Telefone</th>
                                <th>CNPJ</th>
                                <th>Endereço</th>
                                <th>Comprar</th>
                            </thead>
                            {% for supplier in product.supplier_set.all%}
                                <tr>
                                    <td>{{supplier.name}}</td>
                                    <td>{{supplier.telephone}}</td>
                                    <td>{{supplier.cnpj}}</td>
                                    <td>{{supplier.address}}</td>
                                    <td>
                                        <input type="radio" name="supplier" id="supplier-{{supplier.id}}" value="{{supplier.id}}" required>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                        <br>
                        <div class="w3-row w3-margin-top">
                            <div class="w3-col l6  w3-container">
                                <label for="estoqueComprado">Quantidade a comprar</label><br>
                                <input class="w3-input w3-border w3-border-xlarge" type="text" id='estoqueComprado' name="stockToBuy" placeholder="Quantidade a ser comprada" required>
                                <input type="hidden" name="prodId" value="{{product.id}}">
                            </div>
                            <div class="w3-container w3-margin-bottom w3-center">
                                <input type="submit" value="Comprar" class="w3-button w3-lime w3-border w3-round-xlarge w3-margin-top">
                            </div>
                        </div>
                    </form>
                    
                    {%else%}
                        <div class="w3-row">
                            <div class="w3-col l3"><br /></div>
                            <div class="w3-col l6">
                                <div class="w3-panel w3-white w3-bottombar w3-border-amber w3-border">
                                    <p>Não existem Fornecedores para esse Produto</p>
                                </div>
                            </div>
                            <div class="w3-col l3"><br /></div>
                        </div>
                    {% endif %}
                
                </div>
                <div class="w3-left">
                    <a href="{% url 'products:index' %}"
                    class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top"><i class="fa fa-arrow-left"></i> Voltar</a>
                </div>
            </div>
        </div>
    </body>
</html>

comercio/products/templates/products/update.html
<!DOCTYPE html>
<html>
    <head>
        <title>Produtos</title>
        <meta charset="UTF-8">
        {% include 'products/links.html' %}
    </head>
    <body>
        <div class="w3-top w3-overflow">
            {% include 'products/menu.html' %}

            <div class="w3-margin">
                {% if messages %}
                <div class="w3-panel w3-pale-red">
                    <ul class="w3-ul messages">
                        {% for message in messages %}
                        
                        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                    </ul>
                </div>
                {% endif %}

                <p>
                    <b>Produto/Marca: </b>{{ myproduct.name }} / {{ myproduct.brand }}<br/>
                    <b>Preço: </b>{{ myproduct.price }}<br/>
                    <b>Qtde em Estoque: </b>{{ myproduct.stock }}<br/>
                    <b>Qtde em Vendida: </b>{{ myproduct.sold }}<br/>
                </p>

                <div class="w3-container">
                    <div class="w3-bar w3-green">
                        <button class="w3-bar-item w3-button tablink" onclick="openAction(event, 'Atualizar')">Atualizar Produto</button>
                        <button class="w3-bar-item w3-button tablink" onclick="openAction(event, 'Compra')">Compra de Produto</button>
                        <button class="w3-bar-item w3-button tablink" onclick="openAction(event, 'Fornecedor')">Fornecedores do Produto</button>
                    </div>
                    
                    <div id="Atualizar" class="w3-container w3-border acao" style="display:none">
                        <form action="{% url 'products:updaterecord' myproduct.id %}" method="post">
                            {% csrf_token %}
                            <div class="w3-row w3-margin-top">
                                <div class="w3-col l4 w3-container">
                                    <label for="name_field">Nome:</label><br>
                                    <input class="w3-input w3-border w3-round-xlarge" name="name" value="{{ myproduct.name }}" id="name_field" placeholder="Digite um nome" required>
                                </div>
                                <div class="w3-col l4 w3-container">
                                    <label for="">Marca:</label><br>
                                    <input class="w3-input w3-border w3-round-xlarge" name="brand" value="{{ myproduct.brand }}" id="brand_field" placeholder="Digite uma marca" required>
                                </div>
                                <div class="w3-col l4 w3-container">
                                    <label for="price_field">Preço:</label><br>
                                    <input class="w3-input w3-border w3-round-xlarge" name="price" value="{{ myproduct.price }}" id="price_field" placeholder="Digite um preço" required
                                        style="width: 100%;">
                                </div>
                            </div>
                            <div class="w3-row w3-margin-bottom w3-center">
                                <input type="submit" value="Atualizar" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top">
                            </div>
                            
                        </form>
                    </div>
                    
                    <div id="Compra" class="w3-container  w3-border w3-margin-bottom acao" style="display:none">
                        <form action="{% url 'products:buyProduct' myproduct.id %}" method="post">
                            {% csrf_token %}
                            <div class="w3-row w3-margin-top">
                                <div class="w3-col l4 w3-container">
                                    <label for="quantidade_field">Quantidade:</label><br>
                                    <input class="w3-input w3-border w3-round-xlarge" type="number" name="quantidade" id="quantidade_field" placeholder="Digite um número" required>
                                </div>
                            </div>
                            <div class="w3-row w3-margin-bottom w3-center">
                                <input type="submit" value="Comprar" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top">
                            </div>
                        </form>
                    </div>
                    
                    <div id="Fornecedor" class="w3-container w3-border acao" style="display:none">
                        {%if myproduct.supplier_set.all %}
                            <br/>
                            <table class="w3-table w3-striped w3-bordered">
                                <thead class="w3-light-green">
                                    <th>Nome</th>
                                    <th>Telefone</th>
                                    <th>CNPJ</th>
                                    <th>Endereço</th>
                                </thead>
                                {% for supplier in myproduct.supplier_set.all%}
                                    <tr>
                                        <td>{{supplier.name}}</td>
                                        <td>{{supplier.telephone}}</td>
                                        <td>{{supplier.cnpj}}</td>
                                        <td>{{supplier.address}}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        {% else%}
                            <div class="w3-row">
                                <div class="w3-col l3"><br /></div>
                                <div class="w3-col l6">
                                    <div class="w3-panel w3-white w3-bottombar w3-border-amber w3-border">
                                        <p>Não existem Fornecedores para esse Produto</p>
                                    </div>
                                </div>
                                <div class="w3-col l3"><br /></div>
                            </div>
                        {% endif %}
                        <br>
                        {% if myproduct.supplier_set.all %}
                        <form action="{% url 'products:suppliers_of_product' myproduct.id%}">
                            <div class="w3-row w3-margin-bottom w3-center">
                                <input type="submit" name="comprarEstoque" value="Comprar Estoque" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top">
                            </div>
                        </form>
                        {% else%}
                            <p>Para comprar estoque, <a href="{% url 'suppliers:index' %}">associe um Fornecedor à esse Produto</a></p>
                        {% endif %}
                    </div>
                </div>

                <p>
                    <a href="{% url 'products:index' %}" class="w3-button w3-indigo w3-border w3-round-xlarge w3-margin-top"><i class="fa fa-arrow-left"></i> Voltar</a>
                </p>
                
            </div> 
        
        </div>
    </body>
    <script>
        function openAction(evt, acaoName) {
            var i, x, tablinks;
            x = document.getElementsByClassName("acao");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablink");
            for (i = 0; i < x.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" w3-indigo", "");
            }
            document.getElementById(acaoName).style.display = "block";
            evt.currentTarget.className += " w3-indigo";
        }
    </script>
</html>